# Import dependencies

In [1]:
import os, sys

sys.path.append(os.path.abspath("../PDFair"))

import PDFair
import eval
import visualize
import types
import glob
import re
import pandas as pd
import os

[0715 16:41.19 @utils.py:161]  INF  NumExpr defaulting to 16 threads.
/home/marty/miniconda3/envs/test/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[0715 16:41.22 @dd.py:422]  INF  Config:
 {'DEVICE': 'cpu',
 'LANGUAGE': 'nld',
 'LAYOUT_NMS_PAIRS': {'COMBINATIONS': None, 'PRIORITY': None, 'THRESHOLDS': None},
 'LIB': 'PT',
 'OCR': {'CONFIG': {'TESSERACT': 'dd/conf_tesseract.yaml'},
         'USE_DOCTR': False,
         'USE_TESSERACT': True,
         'USE_TEXTRACT': False,
         'WEIGHTS': {'DOCTR_RECOGNITION': {'PT': 'doctr/crnn_vgg16_bn/pt/crnn_vgg16_bn-9762b0b0.pt',
                                           'TF': 'doctr/crnn_vgg16_bn/tf/crnn_vgg16_bn-76b7f2c6.zip'},
                     'DOCTR_WORD': {'PT': 'doctr/db_resnet50/pt/db_resnet50-ac60cadc.pt',
                                    'TF': 'doctr/db_resnet50/tf/db_resnet50-adcafc63.zip'}}},
 'PT': {'CELL': {'FILTER': None,
                 'WEIGHTS': 'cell/d2_model_1849999_cell_inf_only.pt',
                 'WEIGHTS_TS': 'cell/d2_model_1849999_cell_inf_only.ts'},
        'ITEM': {'FILTER': None,
                 'PAD': {'BOTTOM': 60, 'LEFT': 60, 'RIGHT': 60, 'TOP': 60},
                 'WEIGHTS': 'item/d2_model_1639999_item_inf_only.pt',
                 'WEIGHTS_TS': 'item/d2_model_1639999_item_inf_only.ts'},
        'LAYOUT': {'FILTER': None,
                   'PAD': {'BOTTOM': 60, 'LEFT': 60, 'RIGHT': 60, 'TOP': 60},
                   'WEIGHTS': 'layout/d2_model_0829999_layout_inf_only.pt',
                   'WEIGHTS_TS': 'layout/d2_model_0829999_layout_inf_only.ts'}},
 'SEGMENTATION': {'ASSIGNMENT_RULE': 'ioa',
                  'CELL_CATEGORY_ID': 12,
                  'FULL_TABLE_TILING': True,
                  'REMOVE_IOU_THRESHOLD_COLS': 0.001,
                  'REMOVE_IOU_THRESHOLD_ROWS': 0.001,
                  'STRETCH_RULE': 'equal',
                  'THRESHOLD_COLS': 0.4,
                  'THRESHOLD_ROWS': 0.4},
 'TEXT_ORDERING': {'BROKEN_LINE_TOLERANCE': 0.003,
                   'FLOATING_TEXT_BLOCK_CATEGORIES': ['title', 'text', 'list'],
                   'HEIGHT_TOLERANCE': 2.0,
                   'INCLUDE_RESIDUAL_TEXT_CONTAINER': True,
                   'PARAGRAPH_BREAK': 0.035,
                   'STARTING_POINT_TOLERANCE': 0.005,
                   'TEXT_BLOCK_CATEGORIES': ['title', 'text', 'list', 'cell', 'column_header',
                                             'projected_row_header', 'spanning', 'row_header']},
 'TF': {'CELL': {'FILTER': None, 'WEIGHTS': 'cell/model-1800000_inf_only.data-00000-of-00001'},
        'ITEM': {'FILTER': None, 'WEIGHTS': 'item/model-1620000_inf_only.data-00000-of-00001'},
        'LAYOUT': {'FILTER': None, 'WEIGHTS': 'layout/model-800000_inf_only.data-00000-of-00001'}},
 'USE_LAYOUT': True,
 'USE_OCR': True,
 'USE_PDF_MINER': True,
 'USE_TABLE_REFINEMENT': True,
 'USE_TABLE_SEGMENTATION': True,
 'WORD_MATCHING': {'MAX_PARENT_ONLY': True,
                   'PARENTAL_CATEGORIES': ['text', 'title', 'list', 'cell', 'column_header',
                                           'projected_row_header', 'spanning', 'row_header'],
                   'RULE': 'ioa',
                   'THRESHOLD': 0.6}}
[0715 16:41.22 @model.py:970]  ERR  File downloaded from deepdoctection/d2_casc_rcnn_X_32xd4_50_FPN_GN_2FC_publaynet_inference_only does not match the expected size! You may have downloaded a broken file, or the upstream may have modified the file.
[0715 16:41.24 @model.py:970]  ERR  File downloaded from deepdoctection/d2_casc_rcnn_X_32xd4_50_FPN_GN_2FC_pubtabnet_rc_inference_only does not match the expected size! You may have downloaded a broken file, or the upstream may have modified the file.
[0715 16:41.25 @model.py:970]  ERR  File downloaded from deepdoctection/d2_casc_rcnn_X_32xd4_50_FPN_GN_2FC_pubtabnet_c_inference_only does not match the expected size! You may have downloaded a broken file, or the upstream may have modified the file.

# Running PDFair (in batches)
## Loading dataframe

In [2]:
df = pd.DataFrame({
        'dc_source': glob.glob('Pdfs/*'),
        'md': None
    })

df

                                dc_source    md
0  Pdfs/nl.mnre1010.2i.2021.24.misc.1.pdf  None
1   Pdfs/nl.mnre1045.2i.2020.3.misc.1.pdf  None
2  Pdfs/nl.mnre1045.2i.2020.76.misc.1.pdf  None
3  Pdfs/nl.mnre1045.2i.2021.16.misc.1.pdf  None
4  Pdfs/nl.mnre1045.2i.2022.32.misc.1.pdf  None

## Postprocessing functions

In [3]:
# MD: 'A' tag creation on link
pattern_url = r'\b((http(s)?:\/\/)?(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*))\b'

def md_url(match):
    url = match.group(1)
    return f'[{url}]({url})'

# MD: remove double list when not necessary ("* -" > "* ")
pattern_double_list = r'\n((\*|-|\+) (\*|-|\+)) '

def md_double_list(match):
    # url = match.group(1)
    return f'\n* '

def postprocess(text):
    return re.sub(pattern_double_list, md_double_list, re.sub(pattern_url, md_url, text))

## Processing the PDFs

In [14]:
offset = 0
run_n_times = 2
batchsize = 3

def getMd(path):
        try:
            pdf = PDFair.Pdf(path)  # Create Pdf class
            pdf.pdf2doc(max=3)  # Run deepdoctection on first 3 pages (if available)
            for i, _ in enumerate(pdf.pages):
                pdf.pages[i].detect_header()  # Detect headers for page
                pdf.pages[i].doc2md(skip_headers=True)  # Generate markdown (exclude headers)

            return [postprocess(page.md) for page in pdf.pages]  # Postprocess markdown
        except Exception as e:
            return ['FAILED:' + str(e)]

def batch(df, offset, size):
    apply = df[offset:offset+size]  # Create df of batch
    apply['md'] = apply.apply(lambda x: getMd(x['dc_source']), axis=1)  # Generate markdown
    apply.to_json(f'results[{offset}-{offset+len(apply)-1}].json', orient='records', indent=2)  # Save batch

for i in range(offset, offset + batchsize * run_n_times, batchsize):
    batch(df, i, batchsize)

[0715 14:06.03 @doctectionpipe.py:84]  INF  Processing nl.mnre1010.2i.2021.24.misc.1_0.pdf
/home/marty/miniconda3/envs/deepdoc2/lib/python3.9/site-packages/torch/nn/modules/module.py:1527: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3526.)
  return forward_call(*args, **kwargs)
[0715 14:06.09 @context.py:126]  INF  ImageLayoutService total: 4.5387 sec.
[0715 14:06.09 @context.py:126]  INF  SubImageLayoutService total: 0.0001 sec.
[0715 14:06.09 @context.py:126]  INF  SubImageLayoutService total: 0.0 sec.
[0715 14:06.09 @context.py:126]  INF  TableSegmentationService total: 0.0001 sec.
[0715 14:06.09 @context.py:126]  INF  TableSegmentationRefinementService total: 0.0 sec.
[0715 14:06.09 @context.py:126]  INF  TextExtractionService total: 0.1837 sec.
[0715 14:06.09 @context.py:126]  INF  TextExtractionService total: 0.0003 sec.
[0715 14:06.09 @context.py:126]  INF  MatchingService total: 0.0054 sec.
[0715 14:06.09 @context.py:126]  INF  TextOrderService total: 0.0297 sec.
[0715 14:06.09 @doctectionpipe.py:84]  INF  Processing nl.mnre1010.2i.2021.24.misc.1_1.pdf
[0715 14:06.15 @context.py:126]  INF  ImageLayoutService total: 4.3448 sec.
[0715 14:06.15 @context.py:126]  INF  SubImageLayoutService total: 0.0001 sec.
[0715 14:06.15 @context.py:126]  INF  SubImageLayoutService total: 0.0 sec.
[0715 14:06.15 @context.py:126]  INF  TableSegmentationService total: 0.0001 sec.
[0715 14:06.15 @context.py:126]  INF  TableSegmentationRefinementService total: 0.0001 sec.
[0715 14:06.15 @context.py:126]  INF  TextExtractionService total: 0.2076 sec.
[0715 14:06.15 @context.py:126]  INF  TextExtractionService total: 0.0004 sec.
[0715 14:06.15 @context.py:126]  INF  MatchingService total: 0.005 sec.
[0715 14:06.15 @context.py:126]  INF  TextOrderService total: 0.0361 sec.
[0715 14:06.16 @doctectionpipe.py:84]  INF  Processing nl.mnre1010.2i.2021.24.misc.1_2.pdf
[0715 14:06.21 @context.py:126]  INF  ImageLayoutService total: 4.0307 sec.
[0715 14:06.21 @context.py:126]  INF  SubImageLayoutService total: 0.0001 sec.
[0715 14:06.21 @context.py:126]  INF  SubImageLayoutService total: 0.0001 sec.
[0715 14:06.21 @context.py:126]  INF  TableSegmentationService total: 0.0001 sec.
[0715 14:06.21 @context.py:126]  INF  TableSegmentationRefinementService total: 0.0 sec.
[0715 14:06.21 @context.py:126]  INF  TextExtractionService total: 0.051 sec.
[0715 14:06.21 @context.py:126]  INF  TextExtractionService total: 0.0002 sec.
[0715 14:06.21 @context.py:126]  INF  MatchingService total: 0.002 sec.
[0715 14:06.21 @context.py:126]  INF  TextOrderService total: 0.0062 sec.
[0715 14:06.23 @doctectionpipe.py:84]  INF  Processing nl.mnre1045.2i.2020.3.misc.1_0.pdf
[0715 14:06.28 @context.py:126]  INF  ImageLayoutService total: 4.143 sec.
[0715 14:06.28 @context.py:126]  INF  SubImageLayoutService total: 0.0001 sec.
[0715 14:06.28 @context.py:126]  INF  SubImageLayoutService total: 0.0001 sec.
[0715 14:06.28 @context.py:126]  INF  TableSegmentationService total: 0.0001 sec.
[0715 14:06.28 @context.py:126]  INF  TableSegmentationRefinementService total: 0.0001 sec.
[0715 14:06.28 @context.py:126]  INF  TextExtractionService total: 0.0055 sec.
[0715 14:06.29 @context.py:126]  INF  TextExtractionService total: 1.8855 sec.
[0715 14:06.29 @context.py:126]  INF  MatchingService total: 0.004 sec.
[0715 14:06.30 @context.py:126]  INF  TextOrderService total: 0.0252 sec.
[0715 14:06.30 @doctectionpipe.py:84]  INF  Processing nl.mnre1045.2i.2020.3.misc.1_1.pdf
[0715 14:06.35 @context.py:126]  INF  ImageLayoutService total: 4.3302 sec.
[0715 14:06.35 @context.py:126]  INF  SubImageLayoutService total: 0.0002 sec.
[0715 14:06.35 @context.py:126]  INF  SubImageLayoutService total: 0.0001 sec.
[0715 14:06.35 @context.py:126]  INF  TableSegmentationService total: 0.0001 sec.
[0715 14:06.35 @context.py:126]  INF  TableSegmentationRefinementService total: 0.0 sec.
[0715 14:06.35 @context.py:126]  INF  TextExtractionService total: 0.0927 sec.
[0715 14:06.35 @context.py:126]  INF  TextExtractionService total: 0.0006 sec.
[0715 14:06.35 @context.py:126]  INF  MatchingService total: 0.0024 sec.
[0715 14:06.35 @context.py:126]  INF  TextOrderService total: 0.0137 sec.
[0715 14:06.35 @doctectionpipe.py:84]  INF  Processing nl.mnre1045.2i.2020.3.misc.1_2.pdf
[0715 14:06.40 @context.py:126]  INF  ImageLayoutService total: 4.0873 sec.
[0715 14:06.40 @context.py:126]  INF  SubImageLayoutService total: 0.0002 sec.
[0715 14:06.40 @context.py:126]  INF  SubImageLayoutService total: 0.0001 sec.
[0715 14:06.40 @context.py:126]  INF  TableSegmentationService total: 0.0001 sec.
[0715 14:06.40 @context.py:126]  INF  TableSegmentationRefinementService total: 0.0 sec.
[0715 14:06.40 @context.py:126]  INF  TextExtractionService total: 0.0823 sec.
[0715 14:06.40 @context.py:126]  INF  TextExtractionService total: 0.0002 sec.
[0715 14:06.40 @context.py:126]  INF  MatchingService total: 0.0026 sec.
[0715 14:06.40 @context.py:126]  INF  TextOrderService total: 0.0135 sec.
[0715 14:06.41 @doctectionpipe.py:84]  INF  Processing nl.mnre1045.2i.2020.76.misc.1_0.pdf
[0715 14:06.46 @context.py:126]  INF  ImageLayoutService total: 3.9503 sec.
[0715 14:06.46 @context.py:126]  INF  SubImageLayoutService total: 0.0001 sec.
[0715 14:06.46 @context.py:126]  INF  SubImageLayoutService total: 0.0001 sec.
[0715 14:06.46 @context.py:126]  INF  TableSegmentationService total: 0.0001 sec.
[0715 14:06.46 @context.py:126]  INF  TableSegmentationRefinementService total: 0.0001 sec.
[0715 14:06.46 @context.py:126]  INF  TextExtractionService total: 0.1671 sec.
[0715 14:06.46 @context.py:126]  INF  TextExtractionService total: 0.0003 sec.
[0715 14:06.46 @context.py:126]  INF  MatchingService total: 0.0046 sec.
[0715 14:06.46 @context.py:126]  INF  TextOrderService total: 0.0257 sec.
[0715 14:06.47 @doctectionpipe.py:84]  INF  Processing nl.mnre1045.2i.2020.76.misc.1_1.pdf
[0715 14:06.51 @context.py:126]  INF  ImageLayoutService total: 3.7707 sec.
[0715 14:06.51 @context.py:126]  INF  SubImageLayoutService total: 0.0 sec.
[0715 14:06.51 @context.py:126]  INF  SubImageLayoutService total: 0.0 sec.
[0715 14:06.51 @context.py:126]  INF  TableSegmentationService total: 0.0001 sec.
[0715 14:06.51 @context.py:126]  INF  TableSegmentationRefinementService total: 0.0001 sec.
[0715 14:06.52 @context.py:126]  INF  TextExtractionService total: 0.2917 sec.
[0715 14:06.52 @context.py:126]  INF  TextExtractionService total: 0.0005 sec.
[0715 14:06.52 @context.py:126]  INF  MatchingService total: 0.0058 sec.
[0715 14:06.52 @context.py:126]  INF  TextOrderService total: 0.0393 sec.
[0715 14:06.52 @doctectionpipe.py:84]  INF  Processing nl.mnre1045.2i.2020.76.misc.1_2.pdf
[0715 14:06.57 @context.py:126]  INF  ImageLayoutService total: 3.8438 sec.
[0715 14:06.57 @context.py:126]  INF  SubImageLayoutService total: 0.0001 sec.
[0715 14:06.57 @context.py:126]  INF  SubImageLayoutService total: 0.0001 sec.
[0715 14:06.57 @context.py:126]  INF  TableSegmentationService total: 0.0001 sec.
[0715 14:06.57 @context.py:126]  INF  TableSegmentationRefinementService total: 0.0 sec.
[0715 14:06.57 @context.py:126]  INF  TextExtractionService total: 0.2407 sec.
[0715 14:06.57 @context.py:126]  INF  TextExtractionService total: 0.0004 sec.
[0715 14:06.57 @context.py:126]  INF  MatchingService total: 0.004 sec.
[0715 14:06.57 @context.py:126]  INF  TextOrderService total: 0.037 sec.
/tmp/ipykernel_479/3274840610.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  apply['md'] = apply.apply(lambda x: getMd(x['dc_source']), axis=1)  # Generate markdown
[0715 14:06.59 @doctectionpipe.py:84]  INF  Processing nl.mnre1045.2i.2021.16.misc.1_0.pdf
[0715 14:07.04 @context.py:126]  INF  ImageLayoutService total: 3.9698 sec.
[0715 14:07.04 @context.py:126]  INF  SubImageLayoutService total: 0.0001 sec.
[0715 14:07.04 @context.py:126]  INF  SubImageLayoutService total: 0.0001 sec.
[0715 14:07.04 @context.py:126]  INF  TableSegmentationService total: 0.0001 sec.
[0715 14:07.04 @context.py:126]  INF  TableSegmentationRefinementService total: 0.0001 sec.
[0715 14:07.04 @context.py:126]  INF  TextExtractionService total: 0.3042 sec.
[0715 14:07.04 @context.py:126]  INF  TextExtractionService total: 0.0004 sec.
[0715 14:07.04 @context.py:126]  INF  MatchingService total: 0.0038 sec.
[0715 14:07.04 @context.py:126]  INF  TextOrderService total: 0.0381 sec.
[0715 14:07.05 @doctectionpipe.py:84]  INF  Processing nl.mnre1045.2i.2021.16.misc.1_1.pdf
[0715 14:07.10 @context.py:126]  INF  ImageLayoutService total: 4.0612 sec.
[0715 14:07.10 @context.py:126]  INF  SubImageLayoutService total: 0.0002 sec.
[0715 14:07.10 @context.py:126]  INF  SubImageLayoutService total: 0.0001 sec.
[0715 14:07.10 @context.py:126]  INF  TableSegmentationService total: 0.0001 sec.
[0715 14:07.10 @context.py:126]  INF  TableSegmentationRefinementService total: 0.0002 sec.
[0715 14:07.10 @context.py:126]  INF  TextExtractionService total: 0.0067 sec.
[0715 14:07.11 @context.py:126]  INF  TextExtractionService total: 1.4048 sec.
[0715 14:07.11 @context.py:126]  INF  MatchingService total: 0.003 sec.
[0715 14:07.11 @context.py:126]  INF  TextOrderService total: 0.0162 sec.
[0715 14:07.11 @doctectionpipe.py:84]  INF  Processing nl.mnre1045.2i.2021.16.misc.1_2.pdf
[0715 14:07.16 @context.py:126]  INF  ImageLayoutService total: 3.579 sec.
[0715 14:07.16 @context.py:126]  INF  SubImageLayoutService total: 0.0001 sec.
[0715 14:07.16 @context.py:126]  INF  SubImageLayoutService total: 0.0001 sec.
[0715 14:07.16 @context.py:126]  INF  TableSegmentationService total: 0.0001 sec.
[0715 14:07.16 @context.py:126]  INF  TableSegmentationRefinementService total: 0.0 sec.
[0715 14:07.16 @context.py:126]  INF  TextExtractionService total: 0.2159 sec.
[0715 14:07.16 @context.py:126]  INF  TextExtractionService total: 0.0003 sec.
[0715 14:07.16 @context.py:126]  INF  MatchingService total: 0.0041 sec.
[0715 14:07.16 @context.py:126]  INF  TextOrderService total: 0.0254 sec.
[0715 14:07.18 @doctectionpipe.py:84]  INF  Processing nl.mnre1045.2i.2022.32.misc.1_0.pdf
[0715 14:07.22 @context.py:126]  INF  ImageLayoutService total: 3.6362 sec.
[0715 14:07.22 @context.py:126]  INF  SubImageLayoutService total: 0.0001 sec.
[0715 14:07.22 @context.py:126]  INF  SubImageLayoutService total: 0.0001 sec.
[0715 14:07.22 @context.py:126]  INF  TableSegmentationService total: 0.0001 sec.
[0715 14:07.22 @context.py:126]  INF  TableSegmentationRefinementService total: 0.0001 sec.
[0715 14:07.23 @context.py:126]  INF  TextExtractionService total: 0.397 sec.
[0715 14:07.23 @context.py:126]  INF  TextExtractionService total: 0.0007 sec.
[0715 14:07.23 @context.py:126]  INF  MatchingService total: 0.0049 sec.
[0715 14:07.23 @context.py:126]  INF  TextOrderService total: 0.0428 sec.
[0715 14:07.23 @doctectionpipe.py:84]  INF  Processing nl.mnre1045.2i.2022.32.misc.1_1.pdf
[0715 14:07.28 @context.py:126]  INF  ImageLayoutService total: 3.7731 sec.
[0715 14:07.28 @context.py:126]  INF  SubImageLayoutService total: 0.0001 sec.
[0715 14:07.28 @context.py:126]  INF  SubImageLayoutService total: 0.0001 sec.
[0715 14:07.28 @context.py:126]  INF  TableSegmentationService total: 0.0001 sec.
[0715 14:07.28 @context.py:126]  INF  TableSegmentationRefinementService total: 0.0001 sec.
[0715 14:07.28 @context.py:126]  INF  TextExtractionService total: 0.2708 sec.
[0715 14:07.28 @context.py:126]  INF  TextExtractionService total: 0.0004 sec.
[0715 14:07.28 @context.py:126]  INF  MatchingService total: 0.0058 sec.
[0715 14:07.28 @context.py:126]  INF  TextOrderService total: 0.0396 sec.
[0715 14:07.29 @doctectionpipe.py:84]  INF  Processing nl.mnre1045.2i.2022.32.misc.1_2.pdf
[0715 14:07.33 @context.py:126]  INF  ImageLayoutService total: 3.7254 sec.
[0715 14:07.33 @context.py:126]  INF  SubImageLayoutService total: 0.0001 sec.
[0715 14:07.33 @context.py:126]  INF  SubImageLayoutService total: 0.0001 sec.
[0715 14:07.33 @context.py:126]  INF  TableSegmentationService total: 0.0001 sec.
[0715 14:07.33 @context.py:126]  INF  TableSegmentationRefinementService total: 0.0001 sec.
[0715 14:07.33 @context.py:126]  INF  TextExtractionService total: 0.2071 sec.
[0715 14:07.33 @context.py:126]  INF  TextExtractionService total: 0.0003 sec.
[0715 14:07.33 @context.py:126]  INF  MatchingService total: 0.0049 sec.
[0715 14:07.33 @context.py:126]  INF  TextOrderService total: 0.0301 sec.
/tmp/ipykernel_479/3274840610.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  apply['md'] = apply.apply(lambda x: getMd(x['dc_source']), axis=1)  # Generate markdown

## Merging results

In [15]:
results = pd.concat(pd.read_json(file) for file in glob.glob('results*.json')).reset_index(drop=True)

results

,dc_source,md
0,Pdfs/nl.mnre1010.2i.2021.24.misc.1.pdf,[> Retouradres Postbus 20001 2500 EA Den Haag\...
1,Pdfs/nl.mnre1045.2i.2020.3.misc.1.pdf,[Datum 23 januari 2020\n\n\nBetreft Wet openba...
2,Pdfs/nl.mnre1045.2i.2020.76.misc.1.pdf,[Geachte\n\n\nIn uw brief van 20 november 2019...
3,Pdfs/nl.mnre1045.2i.2021.16.misc.1.pdf,[\n* Datum 25 maart 2021 Betreft Besluit inzak...
4,Pdfs/nl.mnre1045.2i.2022.32.misc.1.pdf,[\n* Datum 1 juni 2022 Betreft Besluit Woo-ver...

# Running PDFair (on single PDF)

In [4]:
path = "woobesluit.pdf"

pdf = PDFair.Pdf(path)  # Create Pdf class
pdf.pdf2doc(max=3)  # Run deepdoctection on first 3 pages (if available)
for i, _ in enumerate(pdf.pages):
    pdf.pages[0].detect_header()  # Detect headers for page
    pdf.pages[0].doc2md(skip_headers=True)  # Generate markdown (exclude headers)

print(pdf.pages[0].md)

[0715 16:41.50 @doctectionpipe.py:84]  INF  Processing woobesluit_0.pdf
/home/marty/miniconda3/envs/test/lib/python3.9/site-packages/torch/nn/modules/module.py:1527: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3526.)
  return forward_call(*args, **kwargs)
[0715 16:41.58 @context.py:126]  INF  ImageLayoutService total: 6.0418 sec.
[0715 16:41.58 @context.py:126]  INF  SubImageLayoutService total: 0.0001 sec.
[0715 16:41.58 @context.py:126]  INF  SubImageLayoutService total: 0.0001 sec.
[0715 16:41.58 @context.py:126]  INF  TableSegmentationService total: 0.0001 sec.
[0715 16:41.58 @context.py:126]  INF  TableSegmentationRefinementService total: 0.0001 sec.
[0715 16:41.58 @context.py:126]  INF  TextExtractionService total: 0.3993 sec.
[0715 16:41.58 @context.py:126]  INF  TextExtractionService total: 0.0007 sec.
[0715 16:41.58 @context.py:126]  INF  MatchingService total: 0.0225 sec.
[0715 16:41.58 @context.py:126]  INF  TextOrderService total: 0.1165 sec.
[0715 16:41.59 @doctectionpipe.py:84]  INF  Processing woobesluit_1.pdf
[0715 16:42.05 @context.py:126]  INF  ImageLayoutService total: 4.6792 sec.
[0715 16:42.05 @context.py:126]  INF  SubImageLayoutService total: 0.0001 sec.
[0715 16:42.05 @context.py:126]  INF  SubImageLayoutService total: 0.0001 sec.
[0715 16:42.05 @context.py:126]  INF  TableSegmentationService total: 0.0001 sec.
[0715 16:42.05 @context.py:126]  INF  TableSegmentationRefinementService total: 0.0001 sec.
[0715 16:42.05 @context.py:126]  INF  TextExtractionService total: 0.2694 sec.
[0715 16:42.05 @context.py:126]  INF  TextExtractionService total: 0.001 sec.
[0715 16:42.05 @context.py:126]  INF  MatchingService total: 0.0077 sec.
[0715 16:42.05 @context.py:126]  INF  TextOrderService total: 0.0457 sec.
[0715 16:42.06 @doctectionpipe.py:84]  INF  Processing woobesluit_2.pdf
[0715 16:42.11 @context.py:126]  INF  ImageLayoutService total: 3.9397 sec.
[0715 16:42.11 @context.py:126]  INF  SubImageLayoutService total: 0.0001 sec.
[0715 16:42.11 @context.py:126]  INF  SubImageLayoutService total: 0.0001 sec.
[0715 16:42.11 @context.py:126]  INF  TableSegmentationService total: 0.0001 sec.
[0715 16:42.11 @context.py:126]  INF  TableSegmentationRefinementService total: 0.0 sec.
[0715 16:42.11 @context.py:126]  INF  TextExtractionService total: 0.2668 sec.
[0715 16:42.11 @context.py:126]  INF  TextExtractionService total: 0.0006 sec.
[0715 16:42.11 @context.py:126]  INF  MatchingService total: 0.0061 sec.
[0715 16:42.11 @context.py:126]  INF  TextOrderService total: 0.0654 sec.

## Geachte

,


Per e-mail van 27 juli 2020 heeft u op grond van de Wet openbaarheid van bestuur (hierna: Wob) verzocht om alle bij de Rijksdienst voor het Cultureel Erfgoed (hierna: de RCE) en de Inspectie Overheidsinformatie en Erfgoed (hierna: de inspectie) aanwezige documenten over:



* Onderzoeken naar de bel, periscope en ladder van de HMS E3 in de periode 1 september 2016 tot aan heden;
* De aan het Verenigd Koninkrijk teruggegeven artefacten van de Britse onderzeeërs HMS E3, E5 en E26 in de periode 1 september 2016 tot aan heden;
* De teruggegeven kanonnen van de HMS Victory en La Marquise de Tourny in de periode 1 januari 2010 tot aan heden;
* De inbeslagname van artefacten van de SMS Mainz in de periode 1 januari 2018 tot aan heden.

De ontvangst van uw verzoek is schriftelijk bevestigd bij brief van 10 augustus 2020 met kenmerk 158983. Deze brief heeft u per e-mail ontvangen. In deze brief is de beslistermijn tevens met vier weken verdaagd.


In de brief van 14 september 2020 met kenmerk 158983/2 is aan u medegedeeld dat de beslistermijn is opgeschort met twee weken vanwege het vragen van zienswijzen aan derden. In de brief van 28 september 2020 met kenmerk 158983/3 heb ik de opschorting verlengd met nogmaals twee weken vanwege vertraging in de procedure voor het vragen van zienswijzen aan buitenlandse partijen. Deze brieven heeft u eveneens per e-mail ontvangen. De opschorting is geëindigd op 1 oktober 2020. De uiterste beslisdatum is hiermee 8 oktober 2020 geworden.


## 1. Wettelijk kader

Uw verzoek valt onder de reikwijdte van de Wob. Voor de relevante Wob-artikelen verwijs ik u naar de bijlage 1.


## 2. Inventarisatie documenten

Ten aanzien van het eerste, tweede en vierde punt van uw verzoek zijn in


Pagina 1 van 5

## Generating evaluation visualizations

In [3]:
n = 4

def generate_ngrams(eval):
    eval.pdf2txt()  
    eval.ddt_ngrams(n=n)  # Generate ngrams based on deepdoctection output
    eval.ptt_ngrams(n=n)  # Generate ngrams based on Pdf2text output (run pdf2text() first)

eval = eval.PageEval(pdf.pages[0])  # Create Evaluation class of page
generate_ngrams(eval)
eval.compare_ngrams()  # Mark tokens in missing ngrams as missing (pdf2text ngram is not in deepdoctection output)
eval.ptt.ptttoken_border(n)  # Mark every token with whether it's positioned on a border of two paragraphs

eval.visualize = types.MethodType(visualize.visualize, eval)  # Initialize standard visualization function (own functions can be used as well)
eval.visualize(ignore_header=True, ignore_pdf=False)  # Generate html visualization of page